### ISSUE TITLE
Figure 8 and Eq.2 are difficult to understand for me.

### ISSUE THREAD

**Issue by jingzhengli** [frank-xwang/debiased-pseudo-labeling#5]
Thanks for the nice work.

I understand the mean of CLIP+fixmatch, but what is the mean of CLIP + DebiasPL in tabel 6, is it the CLIP + fixmatch+DebiasPL? In addition, the implementation of CLIP+fixmatch is not to fine tune the CLIP, but only using the pseudo-labels from CLIP on unlabeled data. Do I understand correctly? Thanks.

 I read the paper carefully. But I cannot understand the figure 8 and Eq.2, if there any relevant material to refer to? Thanks,

**Comment by frank-xwang** [comment]
Thanks for your interest in our work. 

For your first question, yes, CLIP + DebiasPL means we use CLIP plus DebiasPL (w/ FixMatch). All the experiments of DebiasPL are based on DebiasPL w/ FixMatch, unless otherwise noted. For zero-shot experiments, we have never used any human annotations. For semi-supervised learning learning experiments,  we use the pseudo-labels from CLIP on unlabeled data for a higher label-efficiency. 

For your second question, you can check references (paper 17, 21, 42, 54) in our [CVPR paper](https://openaccess.thecvf.com/content/CVPR2022/papers/Wang_Debiased_Learning_From_Naturally_Imbalanced_Pseudo-Labels_CVPR_2022_paper.pdf) to better understand the concept of causal inference. 

I hope these answers will be helpful!

**Comment by jingzhengli** [comment]
> Thanks for your interest in our work.
> 
> For your first question, yes, CLIP + DebiasPL means we use CLIP plus DebiasPL (w/ FixMatch). All the experiments of DebiasPL are based on DebiasPL w/ FixMatch, unless otherwise noted. For zero-shot experiments, we have never used any human annotations. For semi-supervised learning learning experiments, we use the pseudo-labels from CLIP on unlabeled data for a higher label-efficiency.
> 
> For your second question, you can check references (paper 17, 21, 42, 54) in our [CVPR paper](https://openaccess.thecvf.com/content/CVPR2022/papers/Wang_Debiased_Learning_From_Naturally_Imbalanced_Pseudo-Labels_CVPR_2022_paper.pdf) to better understand the concept of causal inference.
> 
> I hope these answers will be helpful!

Thanks for you quickly reply. This would be helpful to me.

**Comment by frank-xwang** [comment]
Nice! Closing this issue for now. Feel free to reopen it if you have more questions.
